title: Chenyang Zhang
logo: /src/imgs/0624_SCA.jpg
description: I am an undergraduate student at School of Information Science and Technology, Class of 2022, ShanghaiTech University.
theme: jekyll-theme-minimal